apiVersion: v1
kind: Service
metadata:
  name: nginx-headless-svc
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None                           # Headless Service 지정
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  selector:                                 # StatefulSet이 관리할 Pod 선택 조건 정의
    matchLabels:                            # Pod의 Label과 일치하는 조건 정의
      app: nginx                            # Pod 라벨이 'app: nginx'를 가진 파트 선택 <template: metadata: labels> 와 매칭
  serviceName: "nginx-headless-svc"         # 리소스가 참조할 Headless Service 지정
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx                          # Pod 라벨 'app: nginx' --> matchLables 정의한 라벨과 일치
    spec:
      terminationGracePeriodSeconds: 10     # 종료 대기 시간 -> 종료 시그널 수신 후 10초후 Pod 종료 시작
      containers:
        - name: nginx
          image: k8s.gcr.io/nginx-slim:0.8
          ports:
            - containerPort: 80
              name: web