apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap-blue
data:
  index.html: |    # 멀티라인 문자열 작성할 때 사용, 포멧 유지 -> HTML, JSON, YAML 등 사용 
    <html>
        <body>
            <h1>Welcome to nginx!</h1>
            <h3> = nginx version : v1.17 = </h3>
        </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        version: blue
    spec:
      containers:
        - name: nginx
          image: nginx:1.17
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-index-config-vol
              mountPath:  /usr/share/nginx/html/index.html    # 컨테이너 내부의 파일 시스템 경로 지정
              subPath: index.html                             # 볼륨의 특정 파일이나 디렉터리만 마운트하는 데 사용(아래 volumes path 중 일부)
      volumes:
        - name: nginx-index-config-vol
          configMap:
            name: nginx-configmap-blue
            items:
              - key: index.html                               # ConfigMap의 특정 데이터 (여기서는 data.index.html: )
                path: index.html                              # ConfigMap key에 해당하는 값(데이터) 마운트할 사용 할 내부 파일 이름

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    version: blue  # 기본적으로 Blue 배포에 연결
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ing
spec:
  ingressClassName: nginx
  rules:
    - host: "nginx.211.253.25.128.sslip.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
