apiVersion: v1
kind: Pod
metadata:
  name: test-hostpath-nginx
spec:
  containers:
    - name: test-hostpath-nginx
      image: nginx:1.17
      volumeMounts:
        - mountPath: /var/local/freesia
          name: mydir
        - mountPath: /var/local/freesia/zz.txt
          name: myfile
  volumes:
    - name: mydir
      hostPath:
        path: /var/local/freesia        # 파일 디렉터리가 생성되었는지 확인
        type: DirectoryOrCreate
    - name: myfile
      hostPath:
        path: /var/local/freesia/zz.txt
        type: FileOrCreate