apiVersion: apps/v1                  # API 버전
kind: Deployment                     # kubernetes 리소스 종류 명시
metadata:                            # 리소스(Deployment) 메타정보 정의 블록
  name: nginx-deployment             # Deployment(리스소) 이름, 클러스터 내 식별자
spec:                                # Deployment(리소스) 스펙 정의 블록
  selector:                          # Deployment가 관리할 Pod 선택 조건 정의
    matchLabels:                     # Pod의 Label과 일치하는 조건 정의 
      app: nginx                     # Pod 라벨이 'app: nginx'를 가진 파트 선택 
  replicas: 3                        # 생성할 Pod 개수
  template:                          # 생성할 Pod의 템플릿 정의
    metadata:                        # 생성될 Pod 메타정보 정의 블록 
      labels:                        # 생성될 Pod에 적용할 Label 정의
        app: nginx                   # Pod 라벨 'app: nginx' --> matchLables 정의한 라벨과 일치
    spec:                            # Pod 스펙 정의
      containers:                    # Pod 내 실행될 컨테이너 정의
      - name: nginx                  # 컨테이너 이름
        image: nginx:1.17            # 컨테이너에서 사용할 Docker 이미지 지정
        ports:                       # 컨테이너에서 사용할 포트
        - containerPort: 80          # 컨테이너에서 오픈할 포트